### ISSUE TITLE
Add own sseEmitters Hashmap to GameService

### ISSUE THREAD

**Issue by Eik-S** [soerenreichardt/CastlesIO#30]
- give `GameService` its own sseemitters sending GameStateDTOs to the players
- add subscription request to `GameController`

### why?
we should not send different objects to the same sse connections.
Frontend handles those in the rendered component which is LobbyComponent for lobby ssEemitters and GameComponent for game sseEmitters.

**Comment by soerenreichardt** [comment]
I think with the new event system based implementation this is easily achievable by basically copying what I did for the GameLobby Sse's. A bit of refactoring would be nice to combine both in one abstract class or something.
